quarkus:
  http:
    auth:
      basic: true
    filter:
      ads:
        header:
          "Cache-Control": "public, max-age=3600"
        matches: /ads/.*
        methods: GET

  cache:
    caffeine:
      country-priorities:
        maximum-size: 100
        # Low for testing purposes
        expire-after-write: 10s

  security:
    users:
      embedded:
        enabled: true
        plain-text: true
        users:
          dashboard: dashboard
          processing: processing
        roles:
          dashboard: dashboard
          processing: processing

  # Enable Swagger UI in production
  swagger-ui:
    always-include: true

mp:
  openapi:
    extensions:
      smallrye:
        info:
          title: Ad Mediation API
          version: 1.0.0
          description: API for managing ad network priorities across different countries and platforms
          contact:
            name: API Support
            email: jakob.malezic@gmail.com
        servers:
          - url: http://localhost:8080
            description: Development server
          - url: https://ad-mediation-service-340096700111.europe-west1.run.app
            description: Server on Google Cloud Run
          - url: https://ad-mediation-service.external.blarc.my.id
            description: Server on self-hosted Kubernetes
        security:
          - basicAuth: []


"%test":
  quarkus:
   cache:
    enabled: false